config/routes.rb
Assistant::Application.routes.draw do

  root 'public_page#index'

                #controller, metoda, path


# for subscription
  post '/newsletter' => 'public_page#newsletter', as: :newsletter
  
#search
  get '/search' => 'user#search', as: :search

#session pages 
  post '/register' => 'session#register', as: :register
  post '/login' => 'session#login', as: :login
  get '/logout' => 'session#logout', as: :logout 
  get '/new-user' => 'session#new_user', as: :new_user
  get '/new' => 'session#new', as: :new  
  get '/buy-plan' => 'session#buy_plan', as: :buy_plan
  post '/buy-plan-token' => 'session#buy_plan_token', as: :buy_plan_token
    
#session pages for evercookie
  post '/register-evercookie' => 'session#register_evercookie', as: :register_evercookie
  post '/login-evercookie' => 'session#login_evercookie', as: :login_evercookie
  get '/new-user-evercookie' => 'session#new_user_evercookie', as: :new_user_evercookie
  get '/new-evercookie' => 'session#new_evercookie', as: :new_evercookie
  get '/dashboard-evercookie' => 'session#dashboard_evercookie', as: :dashboard_evercookie
  get '/set-evercookie/:sid' => 'session#set_evercookie', as: :set_evercookie
    
# create companies    
  get '/company/add' => 'company#add', as: :add_company
  post '/company/create' => 'company#create', as: :create_company
  get '/company/edit/:id' => 'company#edit', as: :edit_company
  post '/company/update' => 'company#update', as: :update_company
      
  get '/dashboard' => 'user#dashboard', as: :dashboard
  get '/clients' => 'user#clients', as: :clients
  get '/services' => 'user#services', as: :services
  post '/import/services' => 'services#import', as: :services_import
  get '/materials' => 'user#materials', as: :materials
  get '/stats' => 'user#stats', as: :stats
  get '/appList' => 'user#appList', as: :appList
  get '/checkService' => 'user#services', as: :checkService

  
  post '/clients/create' => 'client#create', as: :create_client
  post '/appointments/create' => 'appointment#create', as: :create_appointment
  post '/send_sms' => 'messages#send_sms', as: :send_sms
  post '/send_reminder' => 'messages#reminder_sms', as: :reminder_sms
  
  get '/client/:id' => 'client#show', as: :client
  get '/edit-client/:id' => 'client#edit', as: :edit_client
  post '/update-client/:id' => 'client#update', as: :update_client
  
  get '/appointment/:id/:first_name/:last_name' => 'appointment#view', as: :view_appointment
  get '/edit-appointment/:id' => 'appointment#edit', as: :edit_appointment
  post '/update-appointment/:id' => 'appointment#update', as: :update_appointment
  delete '/delete-appointment/:id' => 'appointment#destroy', as: :delete_appointment

  post '/services/create' => 'service#create', as: :create_service
  get '/edit-service/:id' => 'service#edit', as: :edit_service
  post '/update-service/:id' => 'service#update', as: :update_service 

  post '/materials/create' => 'material#create', as: :create_material
  get '/edit-material/:id' => 'material#edit', as: :edit_material
  post '/update-material/:id' => 'material#update', as: :update_material

  post '/services/add_material_to_service' => 'service#add_material_to_service', as: :create_servicehasmaterials	

end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  
  skip_before_filter :require_login, except: [:buy_plan, :dashboard_evercookie]
        
  def register
    @user = User.new
    @user.email = params[:email]
    @status = 1

    if params[:email].empty?
        @status = -1
    elsif params[:password] == params[:password_confirmation]
      	    @user.password = params[:password] 
      else
              @status = 0
    end

    respond_to do |format|
      format.html{
        if @status == 1
      	  if @user.save 
            session[:tmp_notice_type] = 'success'
            session[:tmp_notice_message] = 'Welcome!'
            @status = 1
            @messages = "Account created succesfully!"


            stored_session = StoredSession.create!(sid: SecureRandom.hex, user_id: @user[:id])
            cookies[:sid] = stored_session[:sid]

            redirect_to add_company_path
          else
            session[:tmp_notice_type] = 'error'
            session[:tmp_notice_message] = ''
            @status = 0
            @messages = @user.errors  
            redirect_to :back                
          end
        elsif @status == -1
          @password_message = "Please insert an email!"
          redirect_to :back
        else
          @password_message = "Passwords don't match."
          redirect_to :back
        end
      }
    end
  end
  
  def login
  	user = User.authenticate(params[:email], params[:password])
    @usr = user
  	respond_to do |format|
      format.html{
      	if user 
      	    if !cookies[:sid].empty?
      	        stored_session = StoredSession.where(sid: cookies[:sid]).first
      	        stored_session[:user_id] = user[:id]
      	        stored_session.save!
      	    else
      	       stored_session = StoredSession.create(sid: SecureRandom.hex, user_id: user[:id])
                 cookies[:sid] = stored_session[:sid] 
      	    end
      		    #session[:user_id] = user[:id]
              @ok = 1
              redirect_to dashboard_path

              
       	else
            @ok = 0
            redirect_to :back
           
       	end
       	}
   	end
  end	
 
  def new_user
    respond_to do |format|
      format.html{
        render 'new_user.html.erb'
      }
    end
  end
  
  def new_session
    respond_to do |format|
        format.html{
            render 'new.html.erb'
        }
    end
  end

# new actions that use evercookie

  def register_evercookie
  	@user = User.new
  	@user.email = params[:email]
  	@status = 1
  	if params[:email].empty?
  	    @status = -1
  	elsif params[:password] == params[:password_confirmation]
      	    @user.password = params[:password] 
      else
              @status = 0
      end
  	respond_to do |format|
  	   format.js{
      	   if @status == 1
          	   if @user.save 
              	   @message = "Account created succesfully!"
              	   stored_session = StoredSession.create!(sid: SecureRandom.hex, user_id: @user[:id])
              	   @sid = stored_session[:sid]
                   #cookies[:sid] = stored_session[:sid]
                 else
              	   @status = 0
              	   @message = @user.errors 
                 end
              else
                  @message = "Error, please try again"
              end
  	   }
  	end
  end
  
  def login_evercookie
  	user = User.authenticate(params[:email], params[:password])
  	respond_to do |format|
        format.html{
          	if user 
          	    if cookies[:sid] && !cookies[:sid].empty?
          	        stored_session = StoredSession.where(sid: cookies[:sid]).first
          	        stored_session[:user_id] = user[:id]
          	        stored_session.save!
          	        redirect_to dashboard_path
          	    else
          	       stored_session = StoredSession.create!(sid: SecureRandom.hex, user_id: user[:id])
          	       redirect_to set_evercookie_path(stored_session[:sid])

                   #cookies[:sid] = stored_session[:sid] 
          	    end
              #session[:user_id] = user[:id]
           	else
                  redirect_to :back
           	end
       	}
   	end
  end	
 
  def new_user_evercookie
    respond_to do |format|
        format.html{
            render 'new_user_evercookie'
        }
    end
  end
  
  def new_session_evercookie
    respond_to do |format|
        format.html{
            render 'new_evercookie'
        }
    end
  end

  def dashboard_evercookie
        
    @client = Client.new
    @clients = Client.all.where(user_id: current_user[:id])
    
    @appointment = Appointment.new
    @appointments = Appointment.where(user_id: current_user[:id])
    
  	@service = Service.new        
  	@services = Service.where(user_id: current_user[:id])

  	@material = Material.new
  	@materials = Material.where(user_id: current_user[:id])

    respond_to do |format|
        format.html{ render 'dashboard_evercookie'}
    end
  end
  
  def set_evercookie
    @sid = params[:sid]
    render 'set_evercookie'
  end

  # for payments
  def buy_plan   
  end
  
  def buy_plan_token
        token_id = params[:token_id]
         
        Stripe.api_key = "sk_test_wg3jxaKk5jUuB9dZkSTdUVye"
        
        # Get the credit card details submitted by the form
        token = params[:token_id]
        package = params[:package]
        
        # Create the charge on Stripe's servers - this will charge the user's card
        begin
          charge = Stripe::Charge.create(
            :amount => package.to_i * 100, # amount in cents, again
            :currency => "eur",
            :card => token,
            :description => "payinguser@example.com"
          )
        rescue Stripe::CardError => e
          # The card has been declined
        end
        
        if charge.paid == true
            user = User.find_by_id(current_user.id)
            user.package_type = package
            user.save
            
            render :json => 1
        else 
            render :json => 0
        end
  end
  
  def logout
    #session[:user_id] = nil
      if !cookies[:sid].empty?
        stored_session = StoredSession.where(sid: cookies[:sid]).first
        if stored_session
            stored_session.delete
        end
      end
      cookies[:sid] = nil
      respond_to do |format|
         format.html{ redirect_to root_path, notice: 'Logged out.'
         }
      end
  end
 private

  def user_params
    params.require(:user).permit(:avatar)
  end
  
end

app/helpers/session_helper.rb
module SessionHelper
end

app/views/session/buy_plan.html.erb
<script src="https://checkout.stripe.com/checkout.js"></script>

<input type="hidden" id="userEmail" value="<%= @current_user.email %>">
<div class="section section-gray section-buy">
    <div class="container">
        <div class="row" id="price-cards">
            <div class="col-md-10 col-md-offset-1">
                <div class="row">
                    <div class="col-md-4">
                        <div class="card card-price">
                            <div class="content">
                                <h6 class="category">Basic</h6>
                                <h1 class="price">
                                    Free</small>
                                </h1>                        
                                
                                <ul class="list-unstyled list-lines">
                                    <li>
                                        <i class="fa fa-clock-o"></i> <b>30 Days</b> Usage
                                    </li>
                                    <li>
                                        <i class="fa fa-group"></i> <b>5</b> Clients
                                    </li>
                                    <li>
                                        <i class="fa fa-envelope-o"></i> <b>25</b> SMS Notifications
                                    </li>
                                    <li>
                                        <i class="fa fa-level-up"></i> <b>Free</b> Updates
                                    </li>
                                </ul>
                            </div>
                            <div class="footer">
                               <button type="button" onclick="window.location.href='/company/add'" class="btn btn-info btn-block">Get this Package</a>
                            </div>
                        </div> <!-- end card -->
                    </div>   
                     <div class="col-md-4">
                        <div class="card card-price">
                            <div class="content">
                                <h6 class="category">Standard</h6>
                                <h1 class="price">
                                    <small>&euro;</small>19 <small>/mo</small>
                                </h1>                        
                                 <ul class="list-unstyled list-lines">
                                    <li>
                                        <i class="fa fa-clock-o"></i> <b>30 Days</b> Usage
                                    </li>
                                    <li>
                                        <i class="fa fa-group"></i> <b>100</b> Clients
                                    </li>
                                    <li>
                                        <i class="fa fa-envelope-o"></i> <b>500</b> SMS Notifications
                                    </li>
                                    <li>
                                        <i class="fa fa-level-up"></i> <b>Free</b> Updates
                                    </li>
                                </ul>
                            </div>
                            <div class="footer">
                               <button type="button" class="btn btn-info btn-fill btn-block" onclick="getThisPackage(19)">Get this Package</button>
                            </div>
                        </div> <!-- end card -->
                    </div>   
                     <div class="col-md-4">
                        <div class="card card-price">
                            <div class="content">
                                <h6 class="category">Premium</h6>
                                <h1 class="price">
                                    <small>&euro;</small>29 <small>/mo</small>
                                </h1>                        
                                
                                 <ul class="list-unstyled list-lines">
                                    <li>
                                        <i class="fa fa-clock-o"></i> <b>30 Days</b> Usage
                                    </li>
                                    <li>
                                        <i class="fa fa-group"></i> <b>Unlimited </b> Clients
                                    </li>
                                    <li>
                                        <i class="fa fa-envelope-o"></i> <b>Unlimited </b> SMS Notifications
                                    </li>
                                    <li>
                                        <i class="fa fa-level-up"></i> <b>Free</b> Updates
                                    </li>
                                </ul>
                            </div>
                            <div class="footer">
                               <button type="button" class="btn btn-info btn-block" onclick="getThisPackage(29)">Get this Package</button>
                            </div>
                        </div> <!-- end card -->
                    </div>   
                </div>
            </div>
        </div>
    </div>
</div>


<script type="text/javascript">

  // Close Checkout on page navigation
  
  var user_email;
  function getThisPackage(package_price){
        user_email = $('#userEmail').val();
        
        console.log(user_email);
        var handler = StripeCheckout.configure({
            key: 'pk_test_zhUxSpDDRAUNAKnCf5p0ctXX',
            image: '/assets/assistnt_logo-f24a4a97a043adac8f26489d28b7d08e.jpg',
            token: function(token) {
              token_id = token.id;
              
              $.post("/buy-plan-token", "token_id=" + token_id + "&package=" + package_price, function(data) {
                  if(data == 1){
                        window.location.href = "/company/add";  
                  } else {
                        alert('There was an error, please try again');   
                  }
              }, 'json');
              
            }
          });
        
        handler.open({
          name: 'Assistant Plan',
          description: '1 month ($' + package_price +'.00)',
          amount: package_price * 100,
          email: user_email
        }); 
      
      $(window).on('popstate', function() {
        handler.close();
      });
  }

</script>

app/views/session/dashboard_evercookie.html.erb
<%= render partial: 'user/left_menu' %>
<div class="wrapper">
    <div class="container-fluid">
    <div class="row">
        <div class="col-md-12">            
            <div class="row">
                <h3>Calendar</h3>
                <hr>  
            
                <div id="calendar"></div>
              
            </div>    
        </div>
        <div class="col-md-10 col-md-offset-1">         
            <div class="row">
                <h3>Appointments
                    <a type="button" class="btn btn-info btn-fill pull-right" data-trigger="collapseClient" onclick="showNewClientArea(this)"> + New Appointment</a>
                </h3>
                <hr>  
            <div class="col-md-4 col-md-offset-4" id="collapseClient" style="display:none">
                <%= form_for @appointment, url: create_appointment_path, method: 'post', remote: true do |f| %>
                      <div class="form-group">
                          <label>Pacient</label>
                           <% options = options_from_collection_for_select(@clients, 'id', 'name') %>
                           <%= f.select :client_id,  options %>
                          <label>Service Type </label>
                          <% service_options = options_from_collection_for_select(@services, 'id', 'service_name')%>
                          <%= f.select :service_id,  service_options %>
                          <label>Date</label>
                           <%= f.text_field :date, class: "form-control datepicker", placeholder: 'Date', type: 'text' %>
                           <label>Time</label>
                           <%= f.text_field :time, class: "form-control", placeholder: 'Time', type: 'time' %>                          
                      </div>
                         <%= f.button class: "btn btn-info btn-fill" do %>
                             Create Appointment
                         <% end %>

                <% end %>
                <br>
            </div>
                
        <div class="clients-list">
             <table class="table table-striped">
               <tr>
                <th>Client</th>
                <th>Type</th>
                <th>Date</th>
                <th>Time</th>
                <th>Duration</th>
                <th>Actions</th>
            </tr>
            <% @appointments.each do |app| %>
            <% @service = Service.find_by_id(app.service_id) %>
            <% @service_name = @service ? @service.service_name : ''%>
 	    <% @service_duration = @service ? @service.duration.to_i : 0 %>
            
                <tr>
                    <td><%= app.client.name %></td>
                    <td><%= @service_name %></td>
                    <td><%= app.date %></td>
                    <td><%= app.time.to_formatted_s(:time) %></td>
                    <td><%= @service_duration %> min</td>
                    <td><%= link_to 'Edit', edit_appointment_path(app.id) %>
                        <%= link_to 'View', view_appointment_path(id: app.id, first_name: app.client.first_name, last_name: app.client.last_name)%>
                    </td>
                </tr>
            <% end %>
            </table>
        </div>
             
            </div>    
        </div>
    </div>
    </div>
</div>


</div>

<div class="modal fade" id="sendNotificationModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <%= form_tag send_sms_path, method: 'post' do |f| %>
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Send Delay Notification</h4>
      </div>
      <div class="modal-body">
          <div class="form-group">
             <label>Appointment Delay</label>
             <select name="delay">
                 <option value="30">30 minutes</option>
                 <option value="45">45 minutes</option>
                 <option value="60">1 hour</option>
                 <option value="75">1 hour 15 minutes</option>
                 <option value="90">1 hour 30 minutes</option>
                 <option value="120">2 hours</option>
                 <option value="150">2 hours 30 minutes</option>
             </select>
	    
	     <br><br>
	     <label>Only for this pacient</label>
             <input type="checkbox" name="chkOnly1sms" value="1">	 
            
	     <br><br> 
             <input type="hidden" name="appointment_day" id="appointmentDay">  
	     <input type="hidden" name="appointment_id" id="appointmentId"> 	  
             <input type="hidden" name="pacient_telephone" id="pacientTelephone">
             <label>Notice for pacient:</label>
             <%= text_area(:text, :content, rows: 5, class: "form-control", placeholder: 'Write your message here') %>
          </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <%= submit_tag "Send", class: "btn btn-info btn-fill" %>
      </div>
      <% end %>
    </div>
  </div>
</div>

<script type="text/javascript">
    $().ready(function(){
        var date = new Date();
		var d = date.getDate();
		var m = date.getMonth();
		var y = date.getFullYear();
		
		/*  className colors
		
		className: default(transparent), important(red), chill(pink), success(green), info(blue)
		
		*/		
	
	
		/* initialize the calendar
		-----------------------------------------------------------------*/
		
		var calendar =  $('#calendar').fullCalendar({
			header: {
				left: 'title',
				center: 'agendaDay,agendaWeek,month',
				right: 'prev,next today'
			},
			
			firstDay: 1, //  1(Monday) this can be changed to 0(Sunday) for the USA system
			selectable: true,
			defaultView: 'month',
			
			axisFormat: 'h:mm',
			columnFormat: {
                month: 'ddd',    // Mon
                week: 'ddd d', // Mon 7
                day: 'dddd M/d',  // Monday 9/7
                agendaDay: 'dddd d'
            },
            titleFormat: {
                month: 'MMMM yyyy', // September 2009
                week: "MMMM yyyy", // September 2009
                day: 'MMMM yyyy'},
		allDaySlot: false,
		selectHelper: true,
		eventClick: function(calEvent, jsEvent, view) {    			
    			start_date = new moment(calEvent.start);
    			start_date = start_date.format("MMMM Do YYYY, HH:mm");
    			
    			$('#pacientTelephone').val(calEvent.phoneNumber);
    			$('#appointmentDay').val(start_date);
			$('#appointmentId').val(calEvent.appId);
                $('#sendNotificationModal').modal('show');       
            },
			
			events: [
				<% @appointments.each do |app| %>
                    {
			<% @Service = Service.find_by_id(app.service_id) %>
			<% @AppEndTime = app.time + @Service.duration.minutes %>	

                        title: '<%= app.client.name + ' - ' + @Service.service_name %>',
                        start: '<%= app.date %>T<%= app.time.to_formatted_s(:time) %>',
                        end: '<%= app.date %>T<%= @AppEndTime.to_formatted_s(:time) %>',
                        allDay: false,
                        className: 'success',
                        phoneNumber: '<%= app.client.telephone %>',
                        appId:  '<%= app.id %>'
                        
                    },
                <% end %>
			],			
		});
		
    });
</script>

app/views/session/login.js.erb
console.log('<%= @ok %>');
alert("ala");
location.reload();

app/views/session/new.html.erb
<section class="main-section main-section-public">
    <%= render 'partials/navbar' %>
    <div class="content-wrapper">
        <div class="login-container" >
            <div class="container-fluid">
                <div class="row">
                    <div class="col-md-4  col-xs-12 type-6">
                    </div>
                    <div class="col-md-4 col-xs-12 type-6">
                        <div id="card-login-colors" class="card card-login card-blue">
                            <div class="preview">
                                <div class="cardLoginTitle">Login</div>
                            </div>
                            <div class="content" id="inp-login-colors">
                                <%= form_tag login_path, html: {multipart: true}, :method => 'post' do |f| %>
                                    <div class="content" >
                                        <div>
                                            <div class="  email-wrapper inp inp-blue ">
                                                <%= text_field_tag :email,nil, :class => '', :placeholder => 'Email' %>      
                                            </div>
                                            <div class="pass-wrapper inp inp-blue ">
                                                <%= password_field_tag :password,nil, :class => '', :placeholder => 'Password' %>
                                            </div>
                                        </div>
                                        <div  class="btn-login-wrapper">
                                            <%= submit_tag "Login", {class: "btn btn-block btn-lg btn-fill btn-round btn-login btn-blue"} %>
                                        </div> 
                                    </div>
                                <%end%>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4 col-xs-12 type-6">
                </div>
            </div>
        </div>
    </div>
</section>

app/views/session/new_evercookie.html.erb
<%= check_evercookie(:sid) %>
<div class="container" style="margin-top: 100px;">
    <div class="row">
        <div class="col-md-4 col-md-offset-4">
            <div class="well">
                <h3>Login  <small>Let's try it with Evercookie</small></h3>
                <legend></legend>
                <%= form_tag login_evercookie_path, html: {multipart: true}, :method => 'post' do |f|%>
                    <label>Email</label>
                    <%= text_field_tag :email,nil, :class => "form-control", :placeholder => "Email" %>
                    <br /><label>Password</label>
                    <%= password_field_tag :password,nil, :class => "form-control", :placeholder => "Password" %>
                    <br />
                    <%= submit_tag "Login", {class: "btn btn-fill btn-info btn-block"} %>
                <% end	%>
                <br />
                Don't have an account? <%= link_to 'Register', new_user_evercookie_path %>
            </div>
        </div>
    </div>
</div>

app/views/session/new_user.html.erb
<section class="main-section main-section-public">
    <%= render 'partials/navbar' %>
    <div class="content-wrapper">
        <div class="login-container" >
            <div class="container-fluid">
                <div class="row">
                    <div class="col-md-4  col-xs-12 type-6">
                    </div>
                    <div class="col-md-4 col-xs-12 type-6">
                        <div id="card-login-colors" class="card card-login card-blue">
                            <div class="preview">
                                <div class="cardLoginTitle">Register</div>
                            </div>
                            <div class="content" id="inp-login-colors">
                                <%= form_tag register_path, html: {multipart: true}, :method => 'post' do |f| %>
                                    <div class="content" >
                                        <div>
                                            <div class="user-wrapper inp inp-blue">
                                                <%= text_field_tag :first_name,nil, :class => '', :placeholder => 'Name' %>
                                            </div>
                                            <div class="  email-wrapper inp inp-blue ">
                                                <%= text_field_tag :email,nil, :class => '', :placeholder => 'Email' %>      
                                            </div>
                                            <div class="pass-wrapper inp inp-blue ">
                                                <%= password_field_tag :password,nil, :class => '', :placeholder => 'Password' %>
                                            </div>
                                            <div class="  pass-wrapper inp inp-blue">
                                                <%= password_field_tag :password_confirmation,nil, :class => '', :placeholder => 'Repeat Password' %> 
                                            </div>
                                        </div>
                                        <div  class="btn-login-wrapper">
                                            <%= submit_tag "Create account", {class: "btn btn-block btn-lg btn-fill btn-round btn-login btn-blue"} %>
                                        </div> 
                                    </div>
                                <%end%>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4 col-xs-12 type-6">
                </div>
            </div>
        </div>
    </div>
</section>

app/views/session/new_user_evercookie.html.erb
<%= check_evercookie(:sid) %>
<div class="container" style="margin-top: 100px;">
    <div class="row">
        <div class="col-md-4 col-md-offset-4">
            <div class="well">
                <h3>Register <small> Let's try it with Evercookie</small></h3>
                <legend></legend>
                <%= form_tag register_evercookie_path, html: {multipart: true}, :method => 'post', :remote => 'true' do |f| %>
                    <label>Email</label>
                    <%= text_field_tag :email,nil, :class => 'form-control', :placeholder => 'Email' %>
                    <br /><label>Password</label>
                    <%= password_field_tag :password,nil, :class => 'form-control', :placeholder => 'Password' %>
                    <br /><label>Repeat Password</label>
                  	<%= password_field_tag :password_confirmation,nil, :class => 'form-control', :placeholder => 'Repeat Password' %>
                  	<br />
                    <%= submit_tag "Create account", {class: "btn btn-fill btn-info btn-register btn-block"} %>
                <% end	%>
                <br />
                Already have an account? <%= link_to 'Login', new_evercookie_path %>
            </div>
        </div>
    </div>
</div>

app/views/session/register_evercookie.js.erb
console.log('prima parte din post de register' + <%= @status %>);
<% if @status == 1 %>
    window.location.replace("<%= set_evercookie_url(@sid) %>");
<% else %>
    $('.error').append("<%= @message %><br>");
<% end %>

app/views/session/set_evercookie.html.erb
<%= @sid ? set_evercookie(:sid, @sid) : '' %>
<div style="margin-top: 100px;">
    <h2 class="text-center">Welcome! Evercookie has been set! <br /><small><%= link_to 'Dashboard', dashboard_path %></small></h2>
</div>