config/routes.rb
Assistant::Application.routes.draw do

  root 'public_page#index'

                #controller, metoda, path


# for subscription
  post '/newsletter' => 'public_page#newsletter', as: :newsletter
  
#search
  get '/search' => 'user#search', as: :search

#session pages 
  post '/register' => 'session#register', as: :register
  post '/login' => 'session#login', as: :login
  get '/logout' => 'session#logout', as: :logout 
  get '/new-user' => 'session#new_user', as: :new_user
  get '/new' => 'session#new', as: :new  
  get '/buy-plan' => 'session#buy_plan', as: :buy_plan
  post '/buy-plan-token' => 'session#buy_plan_token', as: :buy_plan_token
    
#session pages for evercookie
  post '/register-evercookie' => 'session#register_evercookie', as: :register_evercookie
  post '/login-evercookie' => 'session#login_evercookie', as: :login_evercookie
  get '/new-user-evercookie' => 'session#new_user_evercookie', as: :new_user_evercookie
  get '/new-evercookie' => 'session#new_evercookie', as: :new_evercookie
  get '/dashboard-evercookie' => 'session#dashboard_evercookie', as: :dashboard_evercookie
  get '/set-evercookie/:sid' => 'session#set_evercookie', as: :set_evercookie
    
# create companies    
  get '/company/add' => 'company#add', as: :add_company
  post '/company/create' => 'company#create', as: :create_company
  get '/company/edit/:id' => 'company#edit', as: :edit_company
  post '/company/update' => 'company#update', as: :update_company
      
  get '/dashboard' => 'user#dashboard', as: :dashboard
  get '/clients' => 'user#clients', as: :clients
  get '/services' => 'user#services', as: :services
  post '/import/services' => 'services#import', as: :services_import
  get '/materials' => 'user#materials', as: :materials
  get '/stats' => 'user#stats', as: :stats
  get '/appList' => 'user#appList', as: :appList
  get '/checkService' => 'user#services', as: :checkService

  
  post '/clients/create' => 'client#create', as: :create_client
  post '/appointments/create' => 'appointment#create', as: :create_appointment
  post '/send_sms' => 'messages#send_sms', as: :send_sms
  post '/send_reminder' => 'messages#reminder_sms', as: :reminder_sms
  
  get '/client/:id' => 'client#show', as: :client
  get '/edit-client/:id' => 'client#edit', as: :edit_client
  post '/update-client/:id' => 'client#update', as: :update_client
  
  get '/appointment/:id/:first_name/:last_name' => 'appointment#view', as: :view_appointment
  get '/edit-appointment/:id' => 'appointment#edit', as: :edit_appointment
  post '/update-appointment/:id' => 'appointment#update', as: :update_appointment
  delete '/delete-appointment/:id' => 'appointment#destroy', as: :delete_appointment

  post '/services/create' => 'service#create', as: :create_service
  get '/edit-service/:id' => 'service#edit', as: :edit_service
  post '/update-service/:id' => 'service#update', as: :update_service 

  post '/materials/create' => 'material#create', as: :create_material
  get '/edit-material/:id' => 'material#edit', as: :edit_material
  post '/update-material/:id' => 'material#update', as: :update_material

  post '/services/add_material_to_service' => 'service#add_material_to_service', as: :create_servicehasmaterials	

end

app/models/client.rb
class Client < ActiveRecord::Base

    has_many :appointments

    def name
        name = first_name + ' ' + last_name
    end        
    
    def self.search_clients(search)
        search_item = search.downcase
        if search_item && search_item != ''
            Client.where(last_name: '#{search_item}')
        else
            []
        end
    end


end

app/controllers/client_controller.rb
class ClientController < ApplicationController

  def create
    @client = Client.new(client_params)
    @client.user_id = current_user.id
    if @client.save
        @ok = 1
    else
        @ok = 0
    end
    respond_to do |format|
        format.js{}
    end
  end
  
  def show
    @client = Client.find_by_id(params[:id])
    respond_to do |format|
        format.html{
            render 'client'
        }
    end
  end    
  
  def edit
    @client = Client.find_by_id(params[:id])
    respond_to do |format|
        format.html{
            render 'edit'
        }
    end
  end
  
  def update
    @client = Client.find_by_id(params[:id])
    @ok = @client.update_attributes(client_params)
    respond_to do |format|
        if @ok
          redirect_to clients_path
        else
          redirect_to :back
        end
    end 
  end

   def destroy
    @client = Client.find_by_id(params[:id])
    @client.destroy
    
    redirect_to :back
  end
      
  private

  def client_params
    params.require(:client).permit(:id, :first_name, :last_name, :telephone, :emailC)
  end
  
end

app/helpers/client_helper.rb
module ClientHelper
end

app/views/client/client.html.erb
<section class="main-section">
  <%= render 'partials/navbar' %>
  <div class="content-wrapper">
      <div class="main-container">
        <%= render 'partials/left_menu' %>
          <div class="main-content main-content-with-menu">
            <div class="wrapper">
              <div class="container-fluid">
                <div class="row"> 
                  <div class="col-md-12">                    
                    <div class="header-assistant">
                      <h3 class="pull-left">Appointments of: <%= @client.name %></h3>
                      <%= link_to 'Back', clients_path, class: 'pull-right btn btn-purple' %>
                      <%= link_to 'Edit', edit_client_path, class: 'pull-right btn btn-fill btn-purple' %>
                    </div>
                  </div>
                  <div class="col-md-12">
                    <div class="clients-list">
                      <table class="table table-striped">
                        <tr>
                            <td>Date</td>
                            <td>Time</td>
                            <td>Service</td>
                            <td>Action</td>
                        </tr>
                        <% @client.appointments.each do |app| %>
                            <tr>
                                <td><%= app.date %></td>
                                <td><%= app.time.to_formatted_s(:time) %></td>
                                <td><% @Service = Service.find_by_id(app.service_id) %>
                                    <%= @Service.service_name  %>
                                </td>
                                <td><%= link_to 'Edit', edit_appointment_path(app.id), class: "text-green" %>
                                    <%= link_to 'Delete ', delete_appointment_path(app.id), :method => :delete , class: "text-green" %>
                                </td>
                            </tr>
                        <% end %>
                      </table>
                    </div> 
                  </div>
                </div>     
    
              </div> <!-- container fluid -->
            </div>
          </div>
      </div>
  </div>
</section>

app/views/client/create.js.erb
console.log('<%= @ok %>');
location.reload();

app/views/client/edit.html.erb
<section class="main-section">
  <%= render 'partials/navbar' %>
  <div class="content-wrapper">
      <div class="main-container">
        <%= render 'partials/left_menu' %>
          <div class="main-content main-content-with-menu">
            <div class="wrapper">
              <div class="container-fluid">
                <div class="row"> 
                  <div class="col-md-12">                    
                    <div class="header-assistant">
                      <h3 class="pull-left">Edit: <%= @client.name %></h3>
                      <%= link_to 'Back', client_path, class: 'pull-right btn  btn-purple' %>
                    </div>
                  </div>
                  <div class="col-md-4 col-md-offset-4">
                       <div class="card card-login card-purple card-collapse">
                        <div class="content">
                            <%= form_for @client, url: update_client_path, method: 'post', remote: true do |f| %>
                                <div class=" ">
                                  <div class="inp inp-purple">
                                    <%= f.text_field :first_name, class: "", placeholder: 'First Name', type: 'text' %>
                                  </div>
                                  <div class="inp inp-purple">
                                    <%= f.text_field :last_name, class: "", placeholder: 'Last Name', type: 'text' %>
                                  </div>
                                  <div class="inp inp-purple">
                                    <%= f.text_field :emailC, class: "", placeholder: 'Email', type: 'email' %>
                                  </div>
                                  <div class="inp inp-purple">
                                    <%= f.text_field :telephone, class: "", placeholder: 'Telephone', type: 'text' %>
                                  </div>
                                </div>
                                <%= f.submit "Update", class: "btn btn-fill btn-purple" %>
                              <% end %>
                        </div> 
                      </div>
                  </div>
                </div>     
    
              </div> <!-- container fluid -->
            </div>
          </div>
      </div>
  </div>
</section>

app/views/client/update.js.erb
console.log(<%= @ok %>);
location.reload();