config/routes.rb
Assistant::Application.routes.draw do

  root 'public_page#index'

                #controller, metoda, path


# for subscription
  post '/newsletter' => 'public_page#newsletter', as: :newsletter
  
#search
  get '/search' => 'user#search', as: :search

#session pages 
  post '/register' => 'session#register', as: :register
  post '/login' => 'session#login', as: :login
  get '/logout' => 'session#logout', as: :logout 
  get '/new-user' => 'session#new_user', as: :new_user
  get '/new' => 'session#new', as: :new  
  get '/buy-plan' => 'session#buy_plan', as: :buy_plan
  post '/buy-plan-token' => 'session#buy_plan_token', as: :buy_plan_token
    
#session pages for evercookie
  post '/register-evercookie' => 'session#register_evercookie', as: :register_evercookie
  post '/login-evercookie' => 'session#login_evercookie', as: :login_evercookie
  get '/new-user-evercookie' => 'session#new_user_evercookie', as: :new_user_evercookie
  get '/new-evercookie' => 'session#new_evercookie', as: :new_evercookie
  get '/dashboard-evercookie' => 'session#dashboard_evercookie', as: :dashboard_evercookie
  get '/set-evercookie/:sid' => 'session#set_evercookie', as: :set_evercookie
    
# create companies    
  get '/company/add' => 'company#add', as: :add_company
  post '/company/create' => 'company#create', as: :create_company
  get '/company/edit/:id' => 'company#edit', as: :edit_company
  post '/company/update' => 'company#update', as: :update_company
      
  get '/dashboard' => 'user#dashboard', as: :dashboard
  get '/clients' => 'user#clients', as: :clients
  get '/services' => 'user#services', as: :services
  post '/import/services' => 'services#import', as: :services_import
  get '/materials' => 'user#materials', as: :materials
  get '/stats' => 'user#stats', as: :stats
  get '/appList' => 'user#appList', as: :appList
  get '/checkService' => 'user#services', as: :checkService

  
  post '/clients/create' => 'client#create', as: :create_client
  post '/appointments/create' => 'appointment#create', as: :create_appointment
  post '/send_sms' => 'messages#send_sms', as: :send_sms
  post '/send_reminder' => 'messages#reminder_sms', as: :reminder_sms
  
  get '/client/:id' => 'client#show', as: :client
  get '/edit-client/:id' => 'client#edit', as: :edit_client
  post '/update-client/:id' => 'client#update', as: :update_client
  
  get '/appointment/:id/:first_name/:last_name' => 'appointment#view', as: :view_appointment
  get '/edit-appointment/:id' => 'appointment#edit', as: :edit_appointment
  post '/update-appointment/:id' => 'appointment#update', as: :update_appointment
  delete '/delete-appointment/:id' => 'appointment#destroy', as: :delete_appointment

  post '/services/create' => 'service#create', as: :create_service
  get '/edit-service/:id' => 'service#edit', as: :edit_service
  post '/update-service/:id' => 'service#update', as: :update_service 

  post '/materials/create' => 'material#create', as: :create_material
  get '/edit-material/:id' => 'material#edit', as: :edit_material
  post '/update-material/:id' => 'material#update', as: :update_material

  post '/services/add_material_to_service' => 'service#add_material_to_service', as: :create_servicehasmaterials	

end

app/controllers/public_page_controller.rb
class PublicPageController < ApplicationController
    
    skip_before_filter :require_login

    def index
        render 'index'
    end
    
    def newsletter
#         raise 'here'
        if Gibbon::Request.new(:api_key =>ENV["MAIL_CHIMP_API_KEY"]).lists(ENV["MAIL_CHIMP_DEFAULT_LIST_ID"]).
            members.create(
                body:{
                    :email_address => params[:subscribe_email],
                    status: "subscribed",
                    merge_fields:{FNAME: "jon", LNAME:"doe"}
                    }) 
            @ok = 1
        else
            @ok = 0
        end
        respond_to do |format|
            format.html{
                if @ok
                    redirect_to :back, notice: 'You have been added to the newsletter.'
                else
                    redirect_to :back, alert: 'Something went wrong. Try again!'
                end
            }
        end
    end
    
end

app/helpers/public_page_helper.rb
module PublicPageHelper
end

app/views/public_page/clients.html.erb
<%= render partial: 'public_page/left_menu' %>

<div class="wrapper">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">            
                <div class="row">
                    <h3>Pacients
                        <a type="button" class="btn btn-info btn-fill pull-right" data-trigger="collapseClient" onclick="showNewClientArea(this)"> + New Pacient</a>
                    </h3>
                    <hr>  

                    <div class="col-md-4 col-md-offset-4" id="collapseClient" style="display:none">
                        <%= form_for @client, url: create_client_path, method: 'post', remote: true do |f| %>
                              <div class="form-group">
                                 <label>First Name </label>
                                 <%= f.text_field :first_name, class: "form-control", placeholder: 'First Name', type: 'text' %>
                                 <label>Last Name</label>
                                 <%= f.text_field :last_name, class: "form-control", placeholder: 'Last Name', type: 'text' %>
                                 <label>Email</label>
                                 <%= f.text_field :emailC, class: "form-control", placeholder: 'Email', type: 'email' %>
                                 <label>Phone Number</label>
                                 <%= f.text_field :telephone, class: "form-control", placeholder: 'Telephone', type: 'text' %>
                              </div>
                                 <%= f.button class: "btn btn-info btn-fill" do %>
                                     Create Client
                                 <% end %>
                        <% end %>
                        <br>
                    </div>
                
                    <div class="clients-list">
                        <table class="table table-striped">
                            <tr>
                                <th>Name</th>
                                <th> Email </th>
                                <th>Telephone</th>
                            </tr>
                            <% @clients.each do |client| %>
                                <tr>    
                                <td><%= link_to client.name, client_path(client.id) %></td>
                                <td><%= client.telephone %></td>
                                <td><%= client.emailC %></td>
                                </tr>
                            <% end %>
                        </table>
                    </div>    
                </div>    
            </div>
        </div>
    </div>
</div>

app/views/public_page/index.html.erb
  <section class="main-section main-section-public">
    <%= render 'partials/navbar' %>
    <div class="content-wrapper">
        <div class="main-container">
            <div class="main-content demo-1">
                <div class="public-page-full js " id="scroll-top">
                    <div class="segmenter" style="background-image:url(/images/backgr-1.png)"></div>
                    <h2 class="trigger-headline trigger-headline--hidden">
                        <div >
                            <span>A</span>
                            <span>S</span>
                            <span>S</span>
                            <span>I</span>
                            <span>S</span>
                            <span>T</span>
                            <span>A</span>
                            <span>N</span>
                            <span>T</span>
                        </div>
                    </h2>
                    <p class="headline-text headline-text--hidden">
                        Don't have a a personal assistant? Now is no need to hire one, because Assistant is an application that primarily wants to help the user, in the sense that he can manage his appointment much easier, and sending SMS can be considered a plus to increase the number of clients, because they eliminate the possibility that they forget the time, or wait in case of a delay.
                    </p>

                    <div class="scroll-down">
                        <a class="pe-7s-mouse"></a>
                    </div>
                </div>

                <div class="">
                    <div class="mockup-container">
                        <div class="row">
                            <div class="col-md-6">
                                 <div class="mockup-text">
                                    <h3 class="ebs-title text-red" style="font-weight: 700; text-transform: uppercase;"> Advantages </h3>
                                    <div class="" style=" font-size: 1rem; margin-left: 2rem;">
                                        You can easily manage your entire activity at this office:
                                        <ol style="font-size: 1rem; line-height: 1.5rem; margin-left: 2rem;">
                                            <li><i class="fa fa-check text-red" aria-hidden="true"></i>List of appointments, customers, services and materials;</li>
                                            <li><i class="fa fa-check text-red" aria-hidden="true"></i>Analysis area;</li>
                                            <li><i class="fa fa-check text-red" aria-hidden="true"></i> Excel export with the list of used materials;</li>
                                            <li><i class="fa fa-check text-red" aria-hidden="true"></i> Send SMS reminder to customers;</li>
                                        </ol>
                                    </div>
                                    <div class="" style="font-size: 1rem;margin-left: 2rem; margin-top: 3rem; line-height: 1.5rem;">
                                        To make the user's experience enjoyable in this application, which he is supposed to use several times a day, the interface has been created in accordance with the principles of User Experience Design. We opted for simplicity and clarity, the application being easy to use and quite intuitive by the presence of the buttons specific to the actions that can be performed. We have also tried as much as possible for adding actions, for example, being represented in the same way as the user, whether we are talking about client entities, programming, and service.
                                    </div>
                                 </div>
                            </div>

                             <div class="col-md-6"">
                                 <div class="mockup-image">
                                 </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-4">
                                <div id="test-circle" style="width: 250px; height: 250px;"  data-info="New Clients" data-width="30" data-fontsize="38"></div>
                            </div>
                            <div class="col-md-4">
                                <div id="test-circle-2" style="width: 250px; height: 250px;" ></div>
                            </div>
                            <div class="col-md-4">
                                <div id="test-circle-3" style="width: 250px; height: 250px;" ></div>
                            </div>
                        </div>
                        <div class="row-subscribe">
                            <div class="row">
                                <div class="col-md-4 col-md-offset-3">
                                    <h4>Subscribe for more informations!</h4>
                                </div>
                                <div class="col-md-3 col-md-offset-1" id="subscribe_form">
                                        <%= form_tag newsletter_path, html: {multipart: true},method: 'post' do |f| %>
                                            <div class="inp inp-azure">
                                                <%= text_field_tag :subscribe_email, nil, class: '', placeholder: 'Enter Email', type: 'email' %><br />
                                            </div>
                                             
                                            
                                            <%= submit_tag "Subscribe", {class: "btn btn-azure btn-fill"} %>
                                        <% end  %>    
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="">
                         <footer class="footer block-height-8">        
                            <div class="container">
                                <nav class="pull-left">
                                    <ul>
                                        <li>
                                            <a href="#">
                                                About
                                            </a>
                                        </li>
                                        <li>
                                            <a href="#">
                                                Contact Us
                                            </a>
                                        </li>
                                    </ul>
                                </nav>
                                <div class="social-area pull-right">                
                                    <a href="#">
                                        <i class="fa fa-facebook-square"></i>
                                    </a>
                                    <a href="#">
                                        <i class="fa fa-twitter"></i>
                                    </a>
                                </div>
                                <div class="copyright">
                                    &copy; 2017 Assistant Inc.
                                </div>
                            </div>
                        </footer>
                    </div>
                </div>
            </div>
        </div>

    </div>
    <div class="cd-fail-message">No results found</div>
</section>

<script>
    (function() {
        var headline = document.querySelector('.trigger-headline'),
            headlineText = document.querySelector('.headline-text'),
            segmenter = new Segmenter(document.querySelector('.segmenter'), {
                onReady: setInterval(function() {
                    
                    segmenter.animate();
                    headline.classList.remove('trigger-headline--hidden');
                    headlineText.classList.remove('headline-text--hidden');
                },500)
            });
    })();
</script>

<script type="text/javascript">

    $('.scroll-down .pe-7s-mouse').click(function() {
        $('content-wrapper').animate({
            scrollTop: $("#scroll-top").offset().top
        }, 200);
    });
</script>

<script type="text/javascript">
    $(document).ready(function(){
        $("#test-circle").circliful({
            dimension: 100,
            animationStep: 5,
            foregroundBorderWidth: 5,
            backgroundBorderWidth: 5,
            icon: "none", 
            percent: 80,
            text: "Optimization",
            textStyle: "font-size: 16px; fill: #ddd",   
            textY: "120",                         
            backgroundColor: '#172232',
            foregroundColor: 'rgb(105, 94, 241)',
            fontColor: 'rgb(105, 94, 241)'
        });
        $("#test-circle-2").circliful({
            dimension: 100,
            animationStep: 5,
            foregroundBorderWidth: 5,
            backgroundBorderWidth: 5,
            percent: 65,  
            icon: "none", 
            text: "New Clients",
            textStyle: "font-size: 16px; fill: #ddd",
            textY: "120",                      
            backgroundColor: '#172232',
            foregroundColor: 'rgb(80, 183, 184)',
            fontColor: 'rgb(80, 183, 184)'
        });
        $("#test-circle-3").circliful({
            dimension: 100,
            animationStep: 5,
            foregroundBorderWidth: 5,
            backgroundBorderWidth: 5,
            icon: "none", 
            percent: 75, 
            text: "Productivity",
            textStyle: "font-size: 16px; fill: #ddd",
            textY: "120",         
            backgroundColor: '#172232',
            foregroundColor: 'rgb(224, 99, 101)',
            fontColor: 'rgb(224, 99, 101)'
        });
    });
    
</script>


                        

app/views/public_page/index.xls.erb
  <?xml version="1.0"?>
  <Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:o="urn:schemas-microsoft-com:office:office"
  xmlns:x="urn:schemas-microsoft-com:office:excel"
  xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:html="http://www.w3.org/TR/REC-html40">
  <Worksheet ss:Name="Sheet1">
    <Table>
      <Row>
        <Cell><Data ss:Type="String">Service Name</Data></Cell>
        <Cell><Data ss:Type="String">Duration</Data></Cell>
        <Cell><Data ss:Type="String">Price</Data></Cell>
      </Row>
      <% @services.each do |service| %>
      <Row>
        <Cell><Data ss:Type="Number"><%= service.service_name %></Data></Cell>
        <Cell><Data ss:Type="String"><%= service.duration %></Data></Cell>
        <Cell><Data ss:Type="Number"><%= service.price %></Data></Cell>
      </Row>
      <% end %>
    </Table>
  </Worksheet>
</Workbook>

app/views/public_page/materials.html.erb
<%= render partial: 'public_page/left_menu' %>

<div class="wrapper">
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-12">            
        <div class="row">
          <h3>Materials
            <a type="button" class="btn btn-info btn-fill pull-right" data-trigger="collapseClient" onclick="showNewClientArea(this)"> + New Material</a>
          </h3>
          <hr>  
          <div class="col-md-4 col-md-offset-4" id="collapseClient" style="display:none">
            <%= form_for @material, url: create_material_path, method: 'post', remote: true do |f| %>
            <div class="form-group">
              <label>Material Name </label>
              <%= f.text_field :name, class: "form-control", placeholder: 'Name', type: 'text' %>
              <label>Unit</label>
              <%= f.text_field :unit, class: "form-control", placeholder: 'Unit (gr, ml)', type: 'text' %>
            </div>
            <%= f.button class: "btn btn-info btn-fill" do %>
            Create Material
            <% end %>
            
            <% end %>
            <br>
          </div>
        </div>
        <div class="row">
          <div class="clients-list">
           <table class="table table-striped">
            <tr>
              <th>Material Name</th>
              <th>Unit</th>
            </tr>
            <% @materials.each do |material| %>
            <tr>    
              <td><%= material.name %></td>
              <td><%= material.unit %></td>
            </tr>
            <% end %>
          </table>
        </div>
        
      </div>    
    </div>
  </div>
</div>
</div>

app/views/public_page/services.html.erb
<%= render partial: 'public_page/left_menu' %>

<div class="wrapper">
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-12">            
        <div class="row">
          <h3>Services
            <a type="button" class="btn btn-info btn-fill pull-right" data-trigger="collapseClient" onclick="showNewClientArea(this)"> + New Service</a>
          </h3>
          <hr>  
          <div class="col-md-4 col-md-offset-4" id="collapseClient" style="display:none">
            <%= form_for @service, url: create_service_path, method: 'post', remote: true do |f| %>
            <div class="form-group">
             <label>Service Name </label>
             <%= f.text_field :service_name, class: "form-control", placeholder: 'Name', type: 'text' %>
             <label>Duration</label>
             <%= f.text_field :duration, class: "form-control", placeholder: 'Duration (minutes)', type: 'text' %>
             <label>Price</label>
             <%= f.text_field :price, class: "form-control", placeholder: 'Price', type: 'text' %>
           </div>
           <%= f.button class: "btn btn-info btn-fill" do %>
           Create Service
           <% end %>
           <% end %>
           <br>
         </div>
         
         
         <div class="clients-list">
          <table class="table table-striped">
            <tr>
              <th>Service Name</th>
              <th>Duration</th>
              <th>Price</th>
              <th>Materials</th>
              <th>Action</th>
            </tr>
            <% @services.each do |service| %>
            <tr>    
              <td><%= service.service_name %></td>
              <td><%= service.duration.to_i %> min</td>
              <td>$ <%= service.price %></td>
              <td>   
               <% @materials_string = "" %>
               <% if service.service_has_materials %>
               <% service.service_has_materials.each do |sm| %>
               <% @materials_string = @materials_string + sm.material.name + " " +  sm.quantity.to_s + " " + sm.material.unit + "<br/>" %>
               <% end %>
               <%= @materials_string.html_safe %>
             </td>				
             <td><%= link_to 'Edit', edit_service_path(service.id) %></td>
           </tr>
           <% end %>
           <% end %>
         </table>

       </div>
       
     </div>    
   </div>
 </div>
</div>
</div>