config/routes.rb
Assistant::Application.routes.draw do

  root 'public_page#index'

                #controller, metoda, path


# for subscription
  post '/newsletter' => 'public_page#newsletter', as: :newsletter
  
#search
  get '/search' => 'user#search', as: :search

#session pages 
  post '/register' => 'session#register', as: :register
  post '/login' => 'session#login', as: :login
  get '/logout' => 'session#logout', as: :logout 
  get '/new-user' => 'session#new_user', as: :new_user
  get '/new' => 'session#new', as: :new  
  get '/buy-plan' => 'session#buy_plan', as: :buy_plan
  post '/buy-plan-token' => 'session#buy_plan_token', as: :buy_plan_token
    
#session pages for evercookie
  post '/register-evercookie' => 'session#register_evercookie', as: :register_evercookie
  post '/login-evercookie' => 'session#login_evercookie', as: :login_evercookie
  get '/new-user-evercookie' => 'session#new_user_evercookie', as: :new_user_evercookie
  get '/new-evercookie' => 'session#new_evercookie', as: :new_evercookie
  get '/dashboard-evercookie' => 'session#dashboard_evercookie', as: :dashboard_evercookie
  get '/set-evercookie/:sid' => 'session#set_evercookie', as: :set_evercookie
    
# create companies    
  get '/company/add' => 'company#add', as: :add_company
  post '/company/create' => 'company#create', as: :create_company
  get '/company/edit/:id' => 'company#edit', as: :edit_company
  post '/company/update' => 'company#update', as: :update_company
      
  get '/dashboard' => 'user#dashboard', as: :dashboard
  get '/clients' => 'user#clients', as: :clients
  get '/services' => 'user#services', as: :services
  post '/import/services' => 'services#import', as: :services_import
  get '/materials' => 'user#materials', as: :materials
  get '/stats' => 'user#stats', as: :stats
  get '/appList' => 'user#appList', as: :appList
  get '/checkService' => 'user#services', as: :checkService

  
  post '/clients/create' => 'client#create', as: :create_client
  post '/appointments/create' => 'appointment#create', as: :create_appointment
  post '/send_sms' => 'messages#send_sms', as: :send_sms
  post '/send_reminder' => 'messages#reminder_sms', as: :reminder_sms
  
  get '/client/:id' => 'client#show', as: :client
  get '/edit-client/:id' => 'client#edit', as: :edit_client
  post '/update-client/:id' => 'client#update', as: :update_client
  
  get '/appointment/:id/:first_name/:last_name' => 'appointment#view', as: :view_appointment
  get '/edit-appointment/:id' => 'appointment#edit', as: :edit_appointment
  post '/update-appointment/:id' => 'appointment#update', as: :update_appointment
  delete '/delete-appointment/:id' => 'appointment#destroy', as: :delete_appointment

  post '/services/create' => 'service#create', as: :create_service
  get '/edit-service/:id' => 'service#edit', as: :edit_service
  post '/update-service/:id' => 'service#update', as: :update_service 

  post '/materials/create' => 'material#create', as: :create_material
  get '/edit-material/:id' => 'material#edit', as: :edit_material
  post '/update-material/:id' => 'material#update', as: :update_material

  post '/services/add_material_to_service' => 'service#add_material_to_service', as: :create_servicehasmaterials	

end

app/models/user.rb
class User < ActiveRecord::Base

  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, 
                          :url =>"/assets/users/:id/:style/:basename.:extension",
                          :path =>":rails_root/public/assets/users/:id/:style/:basename.:extension"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/

  require 'rubygems'
  
  include BCrypt

  has_many :appointments
  has_many :services	 

  
  validates :email, presence: true
  validates_uniqueness_of :email
  validates_format_of :email, with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i


  # post '/receive_sms' do 
  #   content_type 'text/xml'

  #   response=Twilio::TwiML::Response.new do |r|
  #     r.Message 'Hey'
  #   end
  #    response.to_xml
  # end

  def send_message(message, app, delay)	

  	@day_and_time = app.date.to_s + " " + app.time.to_formatted_s(:time)	
  	@new_time = app.time + (delay.to_i).minutes		
  	
  	@pacient = Client.find_by_id(app.client_id)
          @phone = '+4' + @pacient.telephone
  	
  	@link = "http://assistant.herokuapp.com/appointment/" + app.id.to_s + "/" + @pacient.first_name + "/" + @pacient.last_name       
    if (delay.to_i).minutes !=0
      @body='"Your appointment from ' + @day_and_time + ' has been rescheduled at ' +  @new_time.to_formatted_s(:time) + '. Notice: ' + message 
                    #+'". You can find more details at this web link: ' + @link
    else
      @body='"Your appointment   has been set at ' +  @new_time.to_formatted_s(:time) + '. Notice: ' + message 
                     #+'". You can find more details at this web link: ' + @link
  	end 
    client = Twilio::REST::Client.new(ENV['TWILIO_SID'], ENV['TWILIO_TOKEN'])
          client.account.messages.create(
          from: ENV['TWILIO_NUMBER'],
          to: @phone,
          body: @body
          )
  end
        
  def password
    if password_hash 
      @password ||= Password.new(password_hash)
    else
      @password = nil 
    end
  end

  def password=(new_password)
    @password = Password.create(new_password)
    self.password_hash = @password
  end

  def self.authenticate(email_param, password_param)
    if @user = find_by_email(email_param)
     if @user.password == password_param
     		@user
     	else
     	  nil
     end
    else
     nil
    end
  end

  def send_password_reset
    generate_token(:password_reset_token)
    self.password_reset_sent_at = Time.zone.now
    save!
    UserMailer.password_reset(self).deliver
  end

  def generate_token(column)
    begin
      self[column] = SecureRandom.urlsafe_base64
    end while User.exists?(column => self[column])
  end

end

app/controllers/user_controller.rb
class UserController < ApplicationController
    require 'uri'
    require 'csv'
    require 'decisiontree'

    
    skip_before_filter :require_login, only: [:search]
    
    def dashboard
        @client = Client.new
        @clients = Client.all.where(user_id: current_user[:id])
        
        @appointment = Appointment.new
        @appointments = Appointment.where(user_id: current_user[:id])
        
    	@service = Service.new        
    	@services = Service.where(user_id: current_user[:id])

    	@material = Material.new
    	@materials = Material.where(user_id: current_user[:id])

    	@month = params[:month]
        @year = params[:year]
            
        if @month && @year
            @time = Time.new(@year,@month)
        else 
            @time = Time.new()
        end
                    
        @appointments_month = Appointment.where('extract(month from date) = ? and extract(year from date) = ? and user_id = ?', @time.month, @time.year, current_user.id).order('created_at asc')        
        @appointments_stats = @appointments_month.group_by{ |appointment| appointment.date.to_date}
    
        @total_appointments_from_month = @appointments_month.count
            
        respond_to do |format|
            format.html{ render 'dashboard'}
        end
    end
    
    def search
        @search = params[:search]
        @clients = Client.search_clients(@search)        
                
        respond_to do |format|
            format.html {render 'search'}
        end 
    end
      
    def clients
        @client = Client.new
        @clients = Client.all.where(user_id: current_user[:id])
        respond_to do |format|
            format.html {}
        end
    end
    
    def services
        @service = Service.new
        @services = Service.where(user_id: current_user[:id])
        @time = Time.new()
        ser= Service.all.where(user_id: current_user[:id])
        app= Appointment.where('extract(month from date) = ? and user_id = ?', @time.month, current_user.id) 
        app2= Appointment.where('extract(month from date) = ? and user_id = ?', @time.month - 1, current_user.id) 
        attributes = ["Duration", "Price"]
        array=[];

        ser.each do | serv |                            
            partArray=[]
            partArray.push(serv.duration.to_i)
            partArray.push(serv.price)
            nr= app.where(:service_id => serv.id).count 
            nr2= app2.where(:service_id => serv.id).count 
            if( ((serv.price/serv.duration.to_i) >=2 && (nr+nr2)>=2) ||  (nr+nr2)>=10)
                partArray.push("profitable".to_s)
            else
                partArray.push("unprofitable".to_s)
            end
            array.push(partArray)

        end 

        dec_tree = DecisionTree::ID3Tree.new(attributes, array, "profitable".to_s, :continuous)
        dec_tree.train
         @val1= params[:dur].to_i
         @val2= params[:pric].to_i
         @okish=0

         puts(@val1)
        
        if @val1!=0
            @okish=1
            test = [@val1, @val2]

            puts(array)
            @decision = dec_tree.predict(test)
        end

        respond_to do |format|
            format.html {}
        end
    end
    
    def materials
        @material = Material.new
        @materials = Material.where(user_id: current_user[:id])
        respond_to do |format|
            format.html {}
            format.xls {send_data @materials.to_csv(col_sep: "\t")}
            format.csv {send_data @materials.to_csv}
        end
    end
    
    def stats
        @apps = Appointment.all.where(user_id: current_user[:id])

        @services= Service.all.where(user_id: current_user[:id])

        @materials= Material.all.where(user_id: current_user[:id])

        @serv_mat= ServiceHasMaterial.all

        @month = params[:month]
        @year = params[:year]
        
        if @month && @year
            @time = Time.new(@year,@month)
        else 
            @time = Time.new()
        end
                
        @appointments_month = Appointment.where('extract(month from date) = ? and extract(year from date) = ? and user_id = ?', @time.month, @time.year, current_user.id).order('created_at asc')        
        @appointments = @appointments_month.group_by{ |appointment| appointment.date.to_date}
    
        @total_appointments_from_month = @appointments_month.count   
    end

    def appList
         @apps= Appointment.all.where(user_id: current_user[:id])
    end

    def check
       

        respond_to do |format|
            format.html{}
         
        end
    end

end

app/helpers/user_helper.rb
module UserHelper
end

app/views/user/_left_menu.html.erb
<div class="left-navbar home-picker block-width-8">
    <ul class="pick-class">
        <li class="placeholder">
            <a  href="/dashboard">
                <i class="fa fa-calendar"></i> 
                Appointments
            </a>
        </li>
        <li class="filter" >
             <a data-type="all" href="/clients">
                <i class="fa fa-group"></i> 
                Clients
            </a>
        </li>
        <li class="filter">
             <a data-type="all" href="/services">
                <i class="fa fa-ticket"></i> 
                Services
            </a>
        </li>
        <li class="filter">
             <a data-type="all" href="/materials">
                <i class="fa fa-magic"></i> 
                Materials
            </a>
        </li>
        <li class="filter">
             <a data-type="all" href="/stats">
                <i class="fa fa-search"></i> 
                Statistics
            </a>
        </li>
        <li class="filter">
             <a data-type="all" href="/company/edit">
                <i class="fa fa-building"></i> 
                Company Informations
            </a>
        </li>
    </ul>
</div>

app/views/user/appList.html.erb
<section class="main-section">
  <%= render 'partials/navbar' %>
  <div class="content-wrapper">
      <div class="main-container">
        <%= render 'partials/left_menu' %>
          <div class="main-content main-content-with-menu">
            <div class="wrapper">
              <div class="container-fluid">
                  <div class="row">
                    <div class="col-md-12">  
                    	<div class="header-assistant">
	                       <h3 class="pull-left">List of appointments</h3>
	                    </div>  
				        <div class="clients-list">
				             <table class="table table-striped">
				               <tr>
				                <th>Client</th>
				                <th>Type</th>
				                <th>Date</th>
				                <th>Time</th>
				                <th>Duration</th>
				                <th>Actions</th>
					            </tr>
					            <% @apps.each do |app| %>
					            <% @service = Service.find_by_id(app.service_id) %>
					            <% @service_name = @service ? @service.service_name : ''%>
					 	    	<% @service_duration = @service ? @service.duration.to_i : 0 %>
					            
					                <tr>
					                    <td><%= app.client.name %></td>
					                    <td><%= @service_name %></td>
					                    <td><%= app.date %></td>
					                    <td><%= app.time.to_formatted_s(:time) %></td>
					                    <td><%= @service_duration %> min</td>
					                    <td><%= link_to 'Edit ', edit_appointment_path(app.id), class: "text-green" %>
					                        <%= link_to 'View', view_appointment_path(id: app.id, first_name: app.client.first_name, last_name: app.client.last_name), class: "text-green"%>
					                        <%= link_to 'Delete ', delete_appointment_path(app.id), :method => :delete, class: "text-green" %>
					                    </td>
					                </tr>

					            <% end %>
				            </table>
				        </div>
				    </div>
                          
                  </div>
              </div> <!-- container fluid -->
          </div>
          </div>
      </div>

  </div>
</section>

app/views/user/checkService.html.erb
<div class="row">
  <%= form_for @service,  url: checkService_path, method: 'post', remote: true do |f| %>
    <div class="form-group">
       <label>Duration</label>
       <%= text_field :duration, class: "form-control", placeholder: 'Duration (minutes)', type: 'text' %>
       <label>Price</label>
       <%= text_field :price, class: "form-control", placeholder: 'Price', type: 'text' %>
    </div>
    <%= f.button class: "btn btn-info btn-fill" do %>
           Create Service
    <% end %>
      <p><%= @decision %></p>
  <%end%>
  </div>

app/views/user/clients.html.erb
<section class="main-section">
  <%= render 'partials/navbar' %>
  <div class="content-wrapper">
      <div class="main-container">
        <%= render 'partials/left_menu' %>
          <div class="main-content main-content-with-menu">
            <div class="wrapper">
              <div class="container-fluid">
                <div class="row"> 
                  <div class="col-md-12">                    
                    <div class="header-assistant">
                       <h3 class="pull-left">Clients</h3>
                        <a type="button" class="btn btn-fill btn-purple pull-right" data-trigger="collapseClient" onclick="showNewClientArea(this)">
                           + New Client
                        </a>
                    </div>
                  </div>
                  <div class="col-md-4 col-md-offset-4" id="collapseClient" style="display:none">
                    <div class="card card-login card-purple card-collapse">
                        <div class="preview">
                          <div class="cardLoginTitle">Add Client</div>
                        </div>
                        <div class="content">
                             <%= form_for @client, url: create_client_path, method: 'post', remote: true do |f| %>
                                <div class="inp inp-purple">
                                  <%= f.text_field :first_name,class: "", placeholder: 'First Name', type: 'text' %>

                                </div>
                                <div class="inp inp-purple">
                                  <%= f.text_field :last_name,class: "", placeholder: 'Last Name', type: 'text' %>
                                </div>
                                <div class="inp inp-purple">
                                  <%= f.text_field :emailC, class: "", placeholder: 'Email', type: 'text'%>
                                </div>
                                <div class="inp inp-purple">
                                  <%= f.text_field :telephone, class: "", placeholder: 'Telephone', type: 'text' %>
                                </div>
                                <%= f.button class: "btn btn-info btn-fill btn-purple" do %>
                                   Save 
                                <% end %>
                              <% end %>
                        </div> 
                      </div>
                  </div>
                </div>     

                <div class="row">            
                  <div class="col-md-12">
                    <div class="clients-list">
                      <table class="table table-striped">
                        <tr>
                          <th>Name</th>
                          <th>Telephone</th>
                          <th>Email</th>
                          <th> Link</th>
                        </tr>
                        <% @clients.each do |client| %>
                          <tr>    
                            <td><%= link_to client.name, client_path(client.id) %></td>
                            <td><%= client.telephone %></td>
                            <td><%= client.emailC %></td>
                            <td><%= link_to 'Edit', edit_client_path(client.id), class: "text-green" %></td>
                          </tr>
                        <% end %>
                      </table>
                    </div> 
                  </div>     
                </div>      
              </div> <!-- container fluid -->
            </div>
          </div>
      </div>
  </div>
</section>

app/views/user/dashboard.html.erb
<section class="main-section">
  <%= render 'partials/navbar' %>
  <div class="content-wrapper">
      <div class="main-container">
        <%= render 'partials/left_menu' %>
          <div class="main-content main-content-with-menu">
            <div class="wrapper">
              <div class="container-fluid">
                  <div class="row">

                    <div class="col-md-12">                    
                      <div class="header-assistant">
                         <h3 class="pull-left">Calendar</h3>
                          <%= link_to 'Appointments', appList_path, class: 'btn btn-fill btn-red pull-right' %>
                          <a type="button" class="btn btn-fill btn-red pull-right" data-trigger="collapseClient" onclick="showNewClientArea(this)">
                             + New Appointment
                          </a>
                      </div>
                    </div>
                    <div class="col-md-4 col-md-offset-4" id="collapseClient" style="display:none">
                      <div class="card card-login card-red card-collapse">
                        <div class="preview">
                          <div class="cardLoginTitle">Add Appointment</div>
                        </div>
                        <div class="content">
                           <%= form_for @appointment, url: create_appointment_path, method: 'post', remote: true do |f| %>
                            <div class="inp inp-red" style="margin: 1rem 0">
                              <% options = options_from_collection_for_select(@clients, 'id', 'name') %>
                               <%= f.select(:client_id, options, {}, {'class' => 'selectpicker', 'data-style' => 'btn btn-red  btn-block' }) %>
                            </div>
                            <div class="inp inp-red" style="margin: 1rem 0">
                              <% service_options = options_from_collection_for_select(@services, 'id', 'service_name')%>
                              <%= f.select(:service_id, service_options, {}, { 'class' => 'selectpicker', 'data-style' => 'btn btn-red btn-block' })%>
                            </div>
                            <div class="inp inp-red">
                              <%= f.text_field :date, class: " datepicker", placeholder: 'Date', type: 'text' %>
                            </div>
                            <div class="inp inp-red">
                              <%= f.text_field :time, class: "form-control", placeholder: 'Time', type: 'time' %>
                            </div>

                            <%= f.button class: "btn btn-red btn-fill", style: "margin-top: 0.5rem" do %>
                             Save 
                            <% end %>
                          <% end %>
                        </div> 
                      </div>
                        
                    </div>      
                  </div>

                  <div class="row">
                    <div class="calendar-container">
                      <div id="calendar"></div>      
                    </div>
                  </div>

              </div> <!-- container fluid -->
          </div>
          </div>
      </div>

  </div>
</section>


<div class="modal fade" id="sendNotificationModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <%= form_tag send_sms_path, method: 'post' do |f| %>
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Send  Notification</h4>
      </div>
      <div class="modal-body">
          <div class="form-group">
            <div class="inp inp-red" style="margin: 1rem 0">
               <select name="delay" placeholder="Select minutes delay">
               <option value="" disabled selected>Select minutes to delay</option>
                 <option value="0"> 0 minutes </option>
                 <option value="30">30 minutes</option>
                 <option value="45">45 minutes</option>
                 <option value="60">1 hour</option>
                 <option value="75">1 hour 15 minutes</option>
                 <option value="90">1 hour 30 minutes</option>
                 <option value="120">2 hours</option>
                 <option value="150">2 hours 30 minutes</option>
             </select>
            </div>
            
            
	      <div class="checkbox checkbox-pink" style="margin: 1rem 0">
            <label>
            <input type="checkbox" name="chkOnly1sms" value="1">
            <i class="helper"></i>
            Only for this pacient
            </label>
        </div>
             <input type="hidden" name="appointment_day" id="appointmentDay">  
	     <input type="hidden" name="appointment_id" id="appointmentId"> 	  
             <input type="hidden" name="pacient_telephone" id="pacientTelephone">
             
             <div class="inp inp-red" style="margin: 1rem 0">
              <%= text_area(:text, :content, rows: 5, class: "", placeholder: 'Write your message here') %>
             </div>
          </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-red btn-fill on-send-loading">Send Message</button>
      </div>
      <% end %>
    </div>
  </div>
</div>

<script type="text/javascript">
    $().ready(function(){
        var date = new Date();
		var d = date.getDate();
		var m = date.getMonth();
		var y = date.getFullYear();
		
		/*  className colors
		
		className: default(transparent), important(red), chill(pink), success(green), info(blue)
		
		*/		
	
	
		/* initialize the calendar
		-----------------------------------------------------------------*/
		
		var calendar =  $('#calendar').fullCalendar({
			header: {
				left: 'title',
				center: 'basicDay,basicWeek,month,listMonth',
				right: 'prev,next today'
			},
			
			firstDay: 1, //  1(Monday) this can be changed to 0(Sunday) for the USA system
			selectable: true,
			defaultView: 'month',
			
			axisFormat: 'h:mm',
			columnFormat: {
                month: 'ddd',    // Mon
                week: 'ddd d', // Mon 7
                day: 'dddd M/d',  // Monday 9/7
                agendaDay: 'dddd d'
            },
            titleFormat: {
                month: 'MMMM yyyy', // September 2009
                week: "MMMM yyyy", // September 2009
                day: 'MMMM yyyy'},
		allDaySlot: false,
		selectHelper: true,
		eventClick: function(calEvent, jsEvent, view) {    			
    			start_date = new moment(calEvent.start);
    			start_date = start_date.format("MMMM Do YYYY, HH:mm");
    			
    			$('#pacientTelephone').val(calEvent.phoneNumber);
    			$('#appointmentDay').val(start_date);
          $('#appointmentId').val(calEvent.appId);
          $('#sendNotificationModal').modal('show');       
    },
			
		events: [
				<% @appointments.each do |app| %>{
    			<% @Service = Service.find_by_id(app.service_id) %>
    			<% @AppEndTime = app.time + @Service.duration.minutes %>	
                title: '<%= app.client.name + ' - ' + @Service.service_name %>',
                start: '<%= app.date %>T<%= app.time.to_formatted_s(:time) %>',
                end: '<%= app.date %>T<%= @AppEndTime.to_formatted_s(:time) %>',
                allDay: false,
                className: 'important',
                phoneNumber: '<%= app.client.telephone %>',
                appId:  '<%= app.id %>',
                
            },
         <% end %>
			],
      

			eventRender: function(event, element) {
                $(element).attr('rel','tooltip').attr('title','Send SMS');
            }			
		});
		
		$('[rel="tooltip"]').tooltip();
    });
    $(function () {
                $('.datepicker').datepicker();
            });

  
</script>

app/views/user/materials.html.erb
<section class="main-section">
  <%= render 'partials/navbar' %>
  <div class="content-wrapper">
      <div class="main-container">
        <%= render 'partials/left_menu' %>
          <div class="main-content main-content-with-menu">
            <div class="wrapper">
              <div class="container-fluid">
                <div class="row"> 
                  <div class="col-md-12">                    
                    <div class="header-assistant">
                       <h3 class="pull-left">Materials</h3>
                        <%= link_to "Export csv", materials_path(format: "csv"), class: "btn btn-default btn-azure pull-right" %> 
                        <%= link_to "Export xls", materials_path(format: "xls"), class: "btn btn-default btn-azure pull-right" %>
                        <a type="button" class="btn  btn-fill btn-azure pull-right" data-trigger="collapseClient" onclick="showNewClientArea(this)">
                           + New Material
                        </a>
                    </div>
                  </div>
                  <div class="col-md-4 col-md-offset-4" id="collapseClient" style="display:none">
                   <div id="card-login-colors" class="card card-login card-azure card-collapse">
                            <div class="preview">
                                <div class="cardLoginTitle">Add Material</div>
                            </div>
                            <div class="content" id="inp-login-colors">
                                 <%= form_for @material, url: create_material_path, method: 'post', remote: true do |f| %>
                                    <div class="inp inp-azure">
                                      <%= f.text_field :name, class: "", placeholder: 'Name', type: 'text' %>
                                    </div>
                                    <div class="inp inp-azure">
                                      <%= f.text_field :unit, class: "", placeholder: 'Unit (gr, ml)', type: 'text' %>
                                    </div>
                                    <div class="inp inp-azure">
                                      <%= f.text_field :price, class: "", placeholder: 'Price/unit ', type: 'text' %>
                                    </div>
                                     <%= f.button class: "btn btn-azure btn-fill" do %>
                                      Save
                                      <% end %>
                                  <% end %>
                            </div>
                        </div>
                     
                      <br>
                  </div>
                </div>     

                <div class="row">            
                  <div class="col-md-12">
                    <div class="clients-list">
                      <table class="table table-striped">
                        <tr>
                            <th>Material Name</th>
                            <th>Units </th>
                            <th>Price</th>
                            <th>Total</th>
                            <th>Action</th>
                        </tr>
                        <% @materials.each do |material| %>
                            <tr>    
                            <td><%= material.name %></td>
                            <td><%= material.unit %></td>
                            <td><%= material.price %> $</td>
                            <td><%= material.price.to_f * material.unit.to_f %> $ </td>
                            <td><%= link_to 'Edit', edit_material_path(material.id), class: 'text-green' %></td>
                            </tr>
                        <% end %>
                      </table>
                    </div> 
                  </div>     
                </div>      
              </div> <!-- container fluid -->
            </div>
          </div>
      </div>
  </div>
</section>

app/views/user/search.html.erb
<div class="search-page">
    <div class="container">
        <div class="col-md-7">
            <h2>
                <small style="border-top: 0px;">Search results:</small> 
                <span class="hello"><%=raw @search %></span>
                
            </h2>
        </div>
        <div class="col-md-5">
            <div class="actions pull-right">
            <p> <%= @decision %></p>
            </div>
        </div>

        
        </div>
        
    </div>
</div>